import Head from 'next/head'
import Header from '../components/layout/header'
import Footer from '../components/layout/footer'
import HeroSection from '../components/hero-section'
import About from '../components/about'
import BrandsSection from '../components/brands'
import ContactSection from '../components/contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Food Options</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroSection />
      <About />
      <BrandsSection />
      <ContactSection />
      <Footer />
    </div>
  )
}
