import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/layout/header'
import Footer from '../components/layout/footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Food Options</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <h1 className={styles.title}>
        Homepage
        </h1>
      </main>
      <Footer/>
    </div>
  )
}
